[project]
name = "urdf2casadi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "casadi>=3.7.2",
    "numpy>=2.3.3",
    "pytest>=8.4.2",
    "urdf-parser-py>=0.0.4",
]
